NAME = ffmpeg
DESC = FFmpeg audio/video filtering library

FFTOOL = ../fftools

HEADERS = $(FFTOOL)/ffmpeg.h

CFLAGS += -DRUN_IN_SDK_MODE=1
OBJS = $(FFTOOL)/ffmpeg.o $(FFTOOL)/ffmpeg.o $(FFTOOL)/ffmpeg_opt.o $(FFTOOL)/ffmpeg_filter.o $(FFTOOL)/ffmpeg_hw.o

