NAME = ffmpeg
DESC = FFmpeg audio/video filtering library

FFTOOL = ../fftools

HEADERS = $(FFTOOL)/ffmpeg.h

OBJS = $(FFTOOL)/ffmpeg.o $(FFTOOL)/ffmpeg_opt.o $(FFTOOL)/ffmpeg_filter.o $(FFTOOL)/ffmpeg_hw.o

