/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.4.1-57-gb276913c7a"
#endif /* AVUTIL_FFVERSION_H */
